version: '3.9'
services:
  app:
    container_name: docker-node-mongodb
    restart: always
    build: .
    ports:
      - "7000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0.3
    ports:
      - "27017:27017"
