version: '3.9'
services:
  mongodb:
    #container_name: my-mongodb-con
    image: mongo:5.0.3
    ports:
     - 27017:27017
    networks:
     - my-mongodb-network
    #volumes:
    #  - my-mongo-volume
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
  my-mongodb-express-con:
    #container_name: my-mongodb-express-con
    image: mongo-express:1.0.0-alpha.4
    ports:
     - 7000:8081
    networks:
     - my-mongodb-network
    #depends_on:
    # - mongodb
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
 my-mongodb-network:
#volumes:
#  my-mongo-volume: